# 외부설정
# classpath : 자바 가상머신이 실행할 때 class파일을 찾는데 그 때 기준이 되는 경로를 의미, spring에서는 이 classpath를 통해 필요한 resources를 가져와 사용한다.
# 프로퍼티 우선 순위
#

spring:
  pid:
    file: boot.pid
  application:
    name: basic
  banner:
    charset: UTF-8
    location: classpath:/banner.txt
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  config:
    import: classpath:daemon.yml, classpath:missing-on-profile.yml
  profiles:
    include:
      - daemon
    group:
      local: daemon-local
      dev: daemon-dev
      live: daemon-live

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  shutdown:
    grace-period: 5000

logging:
  dir: /var/log/${spring.application.name}

log:
  trace:
    file:
      name: trace
      path: ${logging.dir}
  business:
    file:
      name: business
      path: ${logging.dir}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.kyo.basic.process.vo

---
app.name: local
datasource:
  book:
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/book?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kyo
    password: woduf8948!
    connection-test-query: SELECT 1
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000
  test:
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kyo
    password: woduf8948!
    connection-test-query: SELECT 1
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

---
app.name: dev architecture spring-boot 2.4.x (by kyo)
datasource:
  book:
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/book?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kyo
    password: woduf8948!
    connection-test-query: SELECT 1
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000
  test:
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kyo
    password: woduf8948!
    connection-test-query: SELECT 1
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

---
app.name: live architecture spring-boot 2.4.x (by kyo)
datasource:
  book:
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/book?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kyo
    password: woduf8948!
    connection-test-query: SELECT 1
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000
  test:
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kyo
    password: woduf8948!
    connection-test-query: SELECT 1
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

---
### 프로파일 선언 없이 사용하는 상황이 벌어지지 않길 바란다!!
app.name: Oh~ NO~~
