# 외부설정
# classpath : 자바 가상머신이 실행할 때 class파일을 찾는데 그 때 기준이 되는 경로를 의미, spring에서는 이 classpath를 통해 필요한 resources를 가져와 사용한다.
# 프로퍼티 우선 순위
#
spring:
  pid:
    file: boot.pid
  application:
    name: spring-boot-skeleton24x
  config:
    activate:
      on-profile: local
  cache:
    cache-names: samples
  # setting local embedded-redis
  redis:
    host: localhost
    port: 6480
    timeout: 5000
  # setting local embedded-h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  shutdown:
    grace-period: 5000

daemon:
  nick-name: kyo local

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com:
      nexon:
        sampleapi: INFO
  file:
    path: D:/logs/


# apply actuator health,metrics
management:
  endpoints:
    web:
      exposure:
        include: health,metrics


